apiVersion: v1
kind: Service
metadata:
  name: vote-app-svc
spec:
  selector:
    app: vote
    version: v1
    tier: frontend
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32000


      
