apiVersion: v1
kind: Pod
metadata:
  name: vote-app-pod
  labels:
    app: vote
    version: v1
    tier: frontend
spec:
  containers:
    - name: vote-app-container
      image: amitfegade121/vote:v2
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: vote-app-cm
      volumeMounts:
        - name: myvol 
          mountPath: "/etc/config"
          readOnly: true
  volumes:
    - name: myvol
      configMap:
        name: myconfig
