apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-app-deploy
  labels:
    app: vote
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - name: vote-app-container
          image: amitfegade121/vote:v1
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: vote-app-svc
spec:
  selector:
    app: vote
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32000
# We will rolling-out new version of application vote:v2
# We will do rollback to previous stable version
# Different deployment strategies and which strategy by default k8s uses?
# How to see history of rolling-out?
